"""initial schema: campaigns, offers, enrollments

Revision ID: a7015a2faba1
Revises: 
Create Date: 2026-07-06 10:55:09.944230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7015a2faba1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'live', 'ended', name='campaign_status'), nullable=False),
    sa.Column('public_token', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_public_token'), 'campaigns', ['public_token'], unique=True)
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('identity_type', sa.Enum('email', 'phone', name='identity_type'), nullable=False),
    sa.Column('identity_raw', sa.String(length=200), nullable=False),
    sa.Column('identity_normalized', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'identity_normalized', name='uq_enrollment_identity')
    )
    op.create_index(op.f('ix_enrollments_campaign_id'), 'enrollments', ['campaign_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PRODUCT_PERCENT_DISCOUNT', 'CART_FIXED_DISCOUNT', 'STICKER_EARN', name='offer_type'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_campaign_id'), 'offers', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_campaign_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_enrollments_campaign_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_campaigns_public_token'), table_name='campaigns')
    op.drop_table('campaigns')
    sa.Enum(name="campaign_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="offer_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="identity_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
